name: Ebay Scraper (Every 3 hours)

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:        

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          pip install selenium pandas webdriver-manager fake-useragent

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ebay_tech_deals.csv
          git commit -m "Updated eBay data (3-hrs intervals)"
          git push
